### ISSUE TITLE
Can't Start REST server

### ISSUE THREAD

**Issue by calvinKG** [jonniespratley/angular-cms#26]
When I try to start the rest server using (node server) i get the following error 

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Trying to open unclosed connection.
    at NativeConnection.Connection.open (c:\git\CMS\angular-cms-develop\node_mod
ules\mongoose\lib\connection.js:210:15)
    at Mongoose.connect (c:\git\CMS\angular-cms-develop\node_modules\mongoose\li
b\index.js:212:15)
    at Object.ds.connect (c:\git\CMS\angular-cms-develop\node_modules\jps-ds\dis
t\jps-ds.js:54:27)
    at new DS (c:\git\CMS\angular-cms-develop\node_modules\jps-ds\dist\jps-ds.js
:234:17)
    at Object.<anonymous> (c:\git\CMS\angular-cms-develop\routes\rest.js:43:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

**Comment by jonniespratley** [comment]
I am currently working on fixing the multiple connections to MongoDB, but this error will occur if MongoDB is not running on your machine locally. To start mongo just run the following command:

```
$ sh bin/db.sh
```

Then start the node server:

```
$ node server
```

Your error should be gone. Let me know if this solves the issue so we can close it.

**Comment by calvinKG** [comment]
I have edited the db.sh file: 

from: mongod --dbpath db --rest --jsonp;

to: mongod --dbpath C:/mongo_db/MongoDB_2_6/data/db --rest --jsonp;

**Comment by jonniespratley** [comment]
O ok, windows user. ;) 

Ya, not sure if this is cross platform ready yet.

**Comment by calvinKG** [comment]
So this those not run on windows?

**Comment by jonniespratley** [comment]
No, I believe it will run on windows. Just have not fully tested, will make not and add to the list.
